### ISSUE TITLE
When I double click Minepanel.jar nothing happens

### ISSUE THREAD

**Issue by Frityet** [WillEccles/MinePanel#12]

**Comment by WillEccles** [comment]
Could you provide more details, such as OS version, Java version, etc.?

**Comment by Frityet** [comment]
Java 8, Win 10 home

**Comment by Frityet** [comment]
using minecraft server 1.14

**Comment by WillEccles** [comment]
I haven't tested this on Windows in a long time, nor have I used it on any platform, for that matter. However, on Windows, you may want to look into writing a little batch program next to the jar. Place the MinePanel.jar in the same directory as the server.jar, and then write the following batch program (call it something like run.bat):

```batch
@echo off
java -Xmx1024M -Xms1024M -jar minepanel.jar
```

Make sure that Java is in your PATH. For instructions on doing that, [look here](https://stackoverflow.com/a/47902024/2712525).

**Comment by WillEccles** [comment]
No further updates, assuming resolved.
